version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: beautyAndSoul
      DB_USERNAME: root
      DB_PASSWORD: 

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: beautyAndSoul
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge